flaskbb/message/forms.py
# -*- coding: utf-8 -*-
"""
    flaskbb.message.forms
    ~~~~~~~~~~~~~~~~~~~~~

    It provides the forms that are needed for the message views.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, ValidationError, SubmitField
from wtforms.validators import DataRequired
from flask_babelplus import lazy_gettext as _

from flaskbb.user.models import User
from flaskbb.message.models import Conversation, Message


class ConversationForm(FlaskForm):
    to_user = StringField(_("Recipient"), validators=[
        DataRequired(message=_("A valid username is required."))])

    subject = StringField(_("Subject"), validators=[
        DataRequired(message=_("A Subject is required."))])

    message = TextAreaField(_("Message"), validators=[
        DataRequired(message=_("A message is required."))])

    send_message = SubmitField(_("Start Conversation"))
    save_message = SubmitField(_("Save Conversation"))

    def validate_to_user(self, field):
        user = User.query.filter_by(username=field.data).first()
        if not user:
            raise ValidationError(_("The username you entered does not "
                                    "exist."))
        if user.id == current_user.id:
            raise ValidationError(_("You cannot send a PM to yourself."))

    def save(self, from_user, to_user, user_id, unread, as_draft=False,
             shared_id=None):

        conversation = Conversation(
            subject=self.subject.data,
            draft=as_draft,
            shared_id=shared_id,
            from_user_id=from_user,
            to_user_id=to_user,
            user_id=user_id,
            unread=unread
        )
        message = Message(message=self.message.data, user_id=from_user)
        return conversation.save(message=message)


class MessageForm(FlaskForm):
    message = TextAreaField(_("Message"), validators=[
        DataRequired(message=_("A message is required."))])
    submit = SubmitField(_("Send Message"))

    def save(self, conversation, user_id, unread=False):
        """Saves the form data to the model.
        :param conversation: The Conversation object.
        :param user_id: The id from the user who sent the message.
        :param reciever: If the message should also be stored in the recievers
                         inbox.
        """
        message = Message(message=self.message.data, user_id=user_id)

        if unread:
            conversation.unread = True
            conversation.save()
        return message.save(conversation)

flaskbb/message/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.message.views
    ~~~~~~~~~~~~~~~~~~~~~

    The views for the conversations and messages are located in this module.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import uuid

from flask import Blueprint, redirect, request, url_for, flash, abort
from flask_login import login_required, current_user
from flask_babelplus import gettext as _

from flaskbb.extensions import db
from flaskbb.utils.settings import flaskbb_config
from flaskbb.utils.helpers import render_template, format_quote, time_utcnow
from flaskbb.message.forms import ConversationForm, MessageForm
from flaskbb.message.models import Conversation, Message
from flaskbb.user.models import User

message = Blueprint("message", __name__)


@message.route("/")
@message.route("/inbox")
@login_required
def inbox():
    page = request.args.get('page', 1, type=int)

    conversations = Conversation.query.\
        filter(
            Conversation.id == Message.conversation_id,
            Conversation.user_id == current_user.id,
            Conversation.draft == False,
            Conversation.trash == False
        ).\
        order_by(Message.date_created.desc()).\
        paginate(page, flaskbb_config['TOPICS_PER_PAGE'], False)

    message_count = Conversation.query.\
        filter(Conversation.user_id == current_user.id).\
        count()

    return render_template("message/inbox.html", conversations=conversations,
                           message_count=message_count)


@message.route("/<int:conversation_id>/view", methods=["GET", "POST"])
def view_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    if conversation.unread:
        conversation.unread = False
        current_user.invalidate_cache(permissions=False)
        conversation.save()

    form = MessageForm()
    if form.validate_on_submit():

        message_count = Conversation.query.\
            filter(Conversation.user_id == current_user.id).\
            count()

        if message_count >= flaskbb_config["MESSAGE_QUOTA"]:
            flash(_("You cannot send any messages anymore because you have "
                    "reached your message limit."), "danger")
            return redirect(url_for("message.view_conversation",
                                    conversation_id=conversation.id))

        to_user_id = None
        # If the current_user is the user who recieved the message
        # then we have to change the id's a bit.
        if current_user.id == conversation.to_user_id:
            to_user_id = conversation.from_user_id
        else:
            to_user_id = conversation.to_user_id

        form.save(conversation=conversation, user_id=current_user.id)

        # save the message in the recievers conversation
        old_conv = conversation
        conversation = Conversation.query.\
            filter(
                Conversation.user_id == to_user_id,
                Conversation.shared_id == conversation.shared_id
            ).first()

        # user deleted the conversation, start a new conversation with just
        # the recieving message
        if conversation is None:
            conversation = Conversation(
                subject=old_conv.subject,
                from_user_id=current_user.id,
                to_user=to_user_id,
                user_id=to_user_id,
                shared_id=old_conv.shared_id
            )
            conversation.save()

        form.save(conversation=conversation, user_id=current_user.id,
                  unread=True)
        conversation.to_user.invalidate_cache(permissions=False)

        return redirect(url_for("message.view_conversation",
                                conversation_id=old_conv.id))

    return render_template("message/conversation.html",
                           conversation=conversation, form=form)


@message.route("/new", methods=["POST", "GET"])
@login_required
def new_conversation():
    form = ConversationForm()
    to_user = request.args.get("to_user")

    message_count = Conversation.query.\
        filter(Conversation.user_id == current_user.id).\
        count()

    if message_count >= flaskbb_config["MESSAGE_QUOTA"]:
        flash(_("You cannot send any messages anymore because you have "
                "reached your message limit."), "danger")
        return redirect(url_for("message.inbox"))

    if request.method == "POST":
        if "save_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()

            shared_id = uuid.uuid4()

            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=current_user.id,
                      unread=False,
                      as_draft=True,
                      shared_id=shared_id)

            flash(_("Message saved."), "success")
            return redirect(url_for("message.drafts"))

        if "send_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()

            # this is the shared id between conversations because the messages
            # are saved on both ends
            shared_id = uuid.uuid4()

            # Save the message in the current users inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=current_user.id,
                      unread=False,
                      shared_id=shared_id)

            # Save the message in the recievers inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=to_user.id,
                      unread=True,
                      shared_id=shared_id)
            to_user.invalidate_cache(permissions=False)

            flash(_("Message sent."), "success")
            return redirect(url_for("message.sent"))
    else:
        form.to_user.data = to_user

    return render_template("message/message_form.html", form=form,
                           title=_("Compose Message"))


@message.route("/message/<int:message_id>/raw")
@login_required
def raw_message(message_id):
    message = Message.query.filter_by(id=message_id).first_or_404()

    # abort if the message was not the current_user's one or the one of the
    # recieved ones
    if not (message.conversation.from_user_id == current_user.id or
            message.conversation.to_user_id == current_user.id):
        abort(404)

    return format_quote(username=message.user.username,
                        content=message.message)


@message.route("/<int:conversation_id>/edit", methods=["POST", "GET"])
@login_required
def edit_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    if not conversation.draft:
        flash(_("You cannot edit a sent message."), "danger")
        return redirect(url_for("message.inbox"))

    form = ConversationForm()

    if request.method == "POST":
        if "save_message" in request.form:
            to_user = User.query.filter_by(username=form.to_user.data).first()

            conversation.draft = True
            conversation.to_user_id = to_user.id
            conversation.first_message.message = form.message.data
            conversation.save()

            flash(_("Message saved."), "success")
            return redirect(url_for("message.drafts"))

        if "send_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()
            # Save the message in the recievers inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=to_user.id,
                      unread=True,
                      shared_id=conversation.shared_id)

            # Move the message from ``Drafts`` to ``Sent``.
            conversation.draft = False
            conversation.to_user = to_user
            conversation.date_created = time_utcnow()
            conversation.save()

            flash(_("Message sent."), "success")
            return redirect(url_for("message.sent"))
    else:
        form.to_user.data = conversation.to_user.username
        form.subject.data = conversation.subject
        form.message.data = conversation.first_message.message

    return render_template("message/message_form.html", form=form,
                           title=_("Edit Message"))


@message.route("/<int:conversation_id>/move", methods=["POST"])
@login_required
def move_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    conversation.trash = True
    conversation.save()

    return redirect(url_for("message.inbox"))


@message.route("/<int:conversation_id>/restore", methods=["POST"])
@login_required
def restore_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    conversation.trash = False
    conversation.save()
    return redirect(url_for("message.inbox"))


@message.route("/<int:conversation_id>/delete", methods=["POST"])
@login_required
def delete_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    conversation.delete()
    return redirect(url_for("message.inbox"))


@message.route("/sent")
@login_required
def sent():
    page = request.args.get('page', 1, type=int)

    conversations = Conversation.query.\
        filter(
            Conversation.id == Message.conversation_id,

flaskbb/user/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.user.views
    ~~~~~~~~~~~~~~~~~~

    The user view handles the user profile
    and the user settings from a signed in user.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask import Blueprint, flash, request
from flask_login import login_required, current_user
from flask_themes2 import get_themes_list
from flask_babelplus import gettext as _

from flaskbb.extensions import babel
from flaskbb.utils.helpers import render_template
from flaskbb.user.models import User
from flaskbb.user.forms import (ChangePasswordForm, ChangeEmailForm,
                                ChangeUserDetailsForm, GeneralSettingsForm)


user = Blueprint("user", __name__)


@user.route("/<username>")
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template("user/profile.html", user=user)


@user.route("/<username>/topics")
def view_all_topics(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    topics = user.all_topics(page, current_user)
    return render_template("user/all_topics.html", user=user, topics=topics)


@user.route("/<username>/posts")
def view_all_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.all_posts(page, current_user)
    return render_template("user/all_posts.html", user=user, posts=posts)


@user.route("/settings/general", methods=["POST", "GET"])
@login_required
def settings():
    form = GeneralSettingsForm()

    form.theme.choices = [(theme.identifier, theme.name)
                          for theme in get_themes_list()]

    form.language.choices = [(locale.language, locale.display_name)
                             for locale in babel.list_translations()]

    if form.validate_on_submit():
        current_user.theme = form.theme.data
        current_user.language = form.language.data
        current_user.save()

        flash(_("Settings updated."), "success")
    else:
        form.theme.data = current_user.theme
        form.language.data = current_user.language

    return render_template("user/general_settings.html", form=form)


@user.route("/settings/password", methods=["POST", "GET"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        current_user.save()

        flash(_("Password updated."), "success")
    return render_template("user/change_password.html", form=form)


@user.route("/settings/email", methods=["POST", "GET"])
@login_required
def change_email():
    form = ChangeEmailForm(current_user)
    if form.validate_on_submit():
        current_user.email = form.new_email.data
        current_user.save()

        flash(_("Email address updated."), "success")
    return render_template("user/change_email.html", form=form)


@user.route("/settings/user-details", methods=["POST", "GET"])
@login_required
def change_user_details():
    form = ChangeUserDetailsForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()

        flash(_("User details updated."), "success")

    return render_template("user/change_user_details.html", form=form)

flaskbb/templates/message/conversation.html
{% extends theme("message/message_layout.html") %}

{% block message_content %}
{# quick check if the conversation is a draft #}
{% if conversation.draft %}
    {% set messages = [conversation.first_message] %}
{% else %}
    {% set messages = conversation.messages %}
{% endif %}

<div class="panel conversation-panel">
    <div class="panel-heading conversation-head">
        Subject: <strong>{{ conversation.subject }}</strong>
    </div>

    <div class="panel-body conversation-body">
        <div class="conversation-box">
            {% for message in messages %}
            <!-- First Comment -->
            <div class="row conversation-row" id="mid{{message.id}}">
                {% if current_user.id == message.user_id %}
                <div class="col-md-2 col-sm-3 col-xs-12">
                    <div class="conversation-author author">
                        <!-- Registered User -->
                        <div class="author-name"><h4><a href="{{ message.user.url }}">{{ message.user.username }}</a></h4></div>

                        <!-- check if user is online or not -->
                        {% if message.user|is_online %}
                        <div class="author-online" data-toggle="tooltip" data-placement="top" title="online"></div>
                        {% else %}
                        <div class="author-offline" data-toggle="tooltip" data-placement="top" title="offline"></div>
                        {% endif %}
                        <div class="author-title"><h5>{{ message.user.primary_group.name }}</h5></div>

                        {% if message.user.avatar %}
                            <div class="author-avatar"><img src="{{ message.user.avatar }}" alt="avatar"></div>
                        {% endif %}

                        <div class="author-registered">{% trans %}Joined{% endtrans %}: {{ message.user.date_joined|format_date('%b %d %Y') }}</div>
                        <div class="author-posts">{% trans %}Posts{% endtrans %}: {{ message.user.post_count }}</div>

                        {% if message.user.website %}
                        <div class="author-website"><a href="{{ message.user.website }}" rel="nofollow">{% trans %}Website{% endtrans %}</a></div>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                <div class="col-md-10 col-sm-9 col-xs-12">
                    <div class="conversation-message arrow {% if current_user.id == message.user_id %}left{% else %}right{% endif %}">
                        <div class="message-box">

                            <div class="text-left message-header">
                                <time class="conversation-date" datetime="{{ message.date_created }}"><i class="fa fa-clock-o"></i> {{ message.date_created|format_date("%d %B %Y - %H:%M") }}</time>
                            </div>

                            <div class="message-content">
                                {{ message.message|markup }}
                            </div>

                            <div class="message-footer">
                            {% if conversation.draft %}
                                <p class="text-right"><a href="{{ url_for('message.edit_conversation', conversation_id=conversation.id) }}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i> edit</a></p>
                            {% else %}
                                <p class="{% if current_user.id == message.user_id %}left{% else %}right{% endif %}"><a href="#" class="btn btn-default btn-sm reply-btn" data-message-id="{{ message.id }}"><i class="fa fa-reply"></i> reply</a></p>
                            {% endif %}
                            </div>

                        </div>
                    </div>
                </div>
                {% if current_user.id != message.user_id %}
                <div class="col-md-2 col-sm-3 col-xs-12">
                    <div class="conversation-author author">
                        {% if message.user_id and message.user %}
                        <!-- Registered User -->
                        <div class="author-name"><h4><a href="{{ message.user.url }}">{{ message.user.username }}</a></h4></div>

                        <!-- check if user is online or not -->
                        {% if message.user|is_online %}
                        <div class="author-online" data-toggle="tooltip" data-placement="top" title="online"></div>
                        {% else %}
                        <div class="author-offline" data-toggle="tooltip" data-placement="top" title="offline"></div>
                        {% endif %}
                        <div class="author-title"><h5>{{ message.user.primary_group.name }}</h5></div>

                        {% if message.user.avatar %}
                            <div class="author-avatar"><img src="{{ message.user.avatar }}" alt="avatar"></div>
                        {% endif %}

                        <div class="author-registered">{% trans %}Joined{% endtrans %}: {{ message.user.date_joined|format_date('%b %d %Y') }}</div>
                        <div class="author-posts">{% trans %}Posts{% endtrans %}: {{ message.user.post_count }}</div>
                        <div class="author-pm">
                        <a href="{{ url_for('message.new_conversation') }}?to_user={{ message.user.username }}">{% trans %}Message{% endtrans %}</a>
                        </div>

                        {% if message.user.website %}
                        <div class="author-website"><a href="{{ message.user.website }}" rel="nofollow">{% trans %}Website{% endtrans %}</a></div>
                        {% endif %}

                        {% else %}
                        <div class="author-name"><h4>{% trans %}Deleted{% endtrans %}</h4></div>
                        <div class="author-title"><h5>{% trans %}Guest{% endtrans %}</h5></div>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div>
</div>

{% if not conversation.draft %}
{% from "macros.html" import render_quickreply, render_submit_field %}
<form class="form" action="#" method="post">
    {{ form.hidden_tag() }}
    <div class="row conversation-reply">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="editor-box">
                <div class="editor">
                    {{ render_quickreply(form.message, div_class="new-message", rows=7, cols=75, placeholder="", **{'data-provide': 'markdown', 'data-autofocus': 'false', 'class': 'flaskbb-editor'}) }}
                </div>
                <div class="editor-submit">
                    {{ render_submit_field(form.submit, input_class="btn btn-success pull-right") }}
                </div>
            </div>
        </div>
    </div>
    {% include theme('editor_help.html') %}
</form>
{% endif %}

{% endblock %}

{% block scripts %}
    <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock %}

flaskbb/templates/message/conversation_list.html
<div class="panel conversation-panel">
    <div class="panel-heading conversation-head">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="pull-left">
                    <span class="fa fa-comment"></span> {% trans %}Conversations{% endtrans %}
                </div>

                <div class="pull-right">
                    <span class="label label-info">{{ message_count }}/{{ flaskbb_config["MESSAGE_QUOTA"] }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body conversation-body">
        {% for conversation in conversations.items %}
        <div class="row conversation-row hover {% if conversation.unread %}unread{% endif %}">
            <!-- avatar -->
            <div class="col-md-1 col-sm-2 col-xs-2 conversation-avatar">
                {% if conversation.from_user.avatar %}
                <img src="{{ conversation.from_user.avatar }}" class="img-circle" alt="avatar" width="65px" height="65px" />
                {% else %}
                <img src="{{ url_for('static', filename='img/avatar80x80.png') }}" class="img-circle" alt="avatar" width="65px" height="65px" />
                {% endif %}
            </div>
            <!-- other stuff -->
            <div class="col-md-11 col-sm-10 col-xs-10 conversation-info">
                <!-- subject -->
                <div class="conversation-subject">
                    <a href="{{ url_for('message.view_conversation', conversation_id=conversation.id) }}">
                        {% if conversation.unread %}
                            <strong>{{ conversation.subject }}</strong>
                        {% else %}
                            {{ conversation.subject }}
                        {% endif %}
                    </a>
                </div>
                <!-- meta info (date, user) -->
                <div class="conversation-meta">
                    From <a href="{{ conversation.from_user.url }}">{{ conversation.from_user.username }}</a>
                    to <a href="{{ conversation.to_user.url }}">{{ conversation.to_user.username }}</a>
                    on {{ conversation.last_message.date_created|format_date("%d %B %Y - %H:%M") }}
                </div>
                <!-- actual content -->
                <div class="conversation-content">
                    {{ conversation.last_message.message|crop_title(150)|markup }}
                </div>
                <!-- actions -->
                <div class="conversation-actions">
                    {% if include_move %}
                    <form class="inline-form" method="POST" action="{{ url_for('message.move_conversation', conversation_id=conversation.id) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button type="submit" class="btn btn-info btn-xs" title="Move to Trash" data-toggle="tooltip" data-placement="top">
                            <span class="fa fa-archive"></span>
                        </button>
                    </form>
                    {% endif %}

                    {% if include_delete %}
                    <form class="inline-form" method="POST" action="{{ url_for('message.delete_conversation', conversation_id=conversation.id) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button type="submit" class="btn btn-danger btn-xs" title="Delete this conversation" data-toggle="tooltip" data-placement="top">
                            <span class="fa fa-trash"></span>
                        </button>
                    </form>
                    {% endif %}

                    {% if include_restore %}
                    <form class="inline-form" method="POST" action="{{ url_for('message.restore_conversation', conversation_id=conversation.id) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button type="submit" class="btn btn-success btn-xs" title="Restore this conversation" data-toggle="tooltip" data-placement="top">
                            <span class="fa fa-undo"></span>
                        </button>
                    </form>
                    {% endif %}

                    {% if include_edit %}
                    <a class="btn btn-success btn-xs" alt="Edit" title="Edit this conversation" href="{{ url_for('message.edit_conversation', conversation_id = conversation.id) }}" data-toggle="tooltip" data-placement="top">
                        <span class="fa fa-pencil"></span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% else %}
        <div class="row conversation-row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                {% trans %}No conversations found.{% endtrans %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

flaskbb/templates/message/drafts.html
{% set page_title = _("Drafts") %}

{% from theme('macros.html') import render_pagination %}
{% extends theme("message/message_layout.html") %}
{% block message_content %}

{% set include_move = True %}
{% set include_edit = True %}
{% include theme("message/conversation_list.html") %}

{{ render_pagination(conversations, url_for("message.drafts")) }}

{% endblock %}

flaskbb/templates/message/inbox.html
{% set page_title = _("Inbox") %}

{% from theme('macros.html') import render_pagination %}
{% extends theme("message/message_layout.html") %}
{% block message_content %}

{% set include_move = True %}
{% include theme("message/conversation_list.html") %}

{{ render_pagination(conversations, url_for("message.inbox")) }}

{% endblock %}

flaskbb/templates/message/message_layout.html
{% extends theme("layout.html") %}
{% block content %}
{%- from theme('macros.html') import navlink with context -%}

<ol class="breadcrumb flaskbb-breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
    <li><a href="{{ url_for('user.profile', username=current_user.username) }}">{{ current_user.username }}</a></li>
    <li class="active">{% trans %}Private Message{% endtrans %}</li>
</ol>

<div class="row">
    <div class="col-sm-3 col-md-2">
        <div class="sidebar">
            <ul class="nav sidenav">
                <div class="sidenav-btn">
                    <a href="{{ url_for('message.new_conversation') }}" class="btn btn-success">{% trans %}New Message{% endtrans %}</a>
                </div>
                {{ navlink('message.inbox', _('Inbox')) }}
                {{ navlink('message.sent', _('Sent')) }}
                {{ navlink('message.drafts', _('Drafts')) }}
                {{ navlink('message.trash', _('Trash')) }}
            </ul>
        </div><!--/.sidebar -->
    </div><!--/.col-sm-3 -->
    <div class="col-sm-9 col-md-10">
        {% block message_content %}{% endblock %}
    </div><!--/.col-sm-9 -->
</div><!--/.row -->
{% endblock %}


{% block scripts %}
    <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock %}

flaskbb/templates/message/sent.html
{% set page_title = _("Sent Messages") %}

{% from theme('macros.html') import render_pagination %}
{% extends theme("message/message_layout.html") %}
{% block message_content %}

{% set include_move = True %}
{% include theme("message/conversation_list.html") %}

{{ render_pagination(conversations, url_for("message.sent")) }}

{% endblock %}

flaskbb/templates/message/trash.html
{% set page_title = _("Trash") %}

{% from theme('macros.html') import render_pagination %}
{% extends theme("message/message_layout.html") %}
{% block message_content %}

{% set include_restore = True %}
{% set include_delete = True %}
{% include theme("message/conversation_list.html") %}

{{ render_pagination(conversations, url_for("message.trash")) }}

{% endblock %}