flaskbb/message/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.message.views
    ~~~~~~~~~~~~~~~~~~~~~

    The views for the conversations and messages are located in this module.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import uuid

from flask import Blueprint, redirect, request, url_for, flash, abort
from flask_login import login_required, current_user
from flask_babelplus import gettext as _

from flaskbb.extensions import db
from flaskbb.utils.settings import flaskbb_config
from flaskbb.utils.helpers import render_template, format_quote, time_utcnow
from flaskbb.message.forms import ConversationForm, MessageForm
from flaskbb.message.models import Conversation, Message
from flaskbb.user.models import User

message = Blueprint("message", __name__)


@message.route("/")
@message.route("/inbox")
@login_required
def inbox():
    page = request.args.get('page', 1, type=int)

    conversations = Conversation.query.\
        filter(
            Conversation.id == Message.conversation_id,
            Conversation.user_id == current_user.id,
            Conversation.draft == False,
            Conversation.trash == False
        ).\
        order_by(Message.date_created.desc()).\
        paginate(page, flaskbb_config['TOPICS_PER_PAGE'], False)

    message_count = Conversation.query.\
        filter(Conversation.user_id == current_user.id).\
        count()

    return render_template("message/inbox.html", conversations=conversations,
                           message_count=message_count)


@message.route("/<int:conversation_id>/view", methods=["GET", "POST"])
def view_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    if conversation.unread:
        conversation.unread = False
        current_user.invalidate_cache(permissions=False)
        conversation.save()

    form = MessageForm()
    if form.validate_on_submit():

        message_count = Conversation.query.\
            filter(Conversation.user_id == current_user.id).\
            count()

        if message_count >= flaskbb_config["MESSAGE_QUOTA"]:
            flash(_("You cannot send any messages anymore because you have "
                    "reached your message limit."), "danger")
            return redirect(url_for("message.view_conversation",
                                    conversation_id=conversation.id))

        to_user_id = None
        # If the current_user is the user who recieved the message
        # then we have to change the id's a bit.
        if current_user.id == conversation.to_user_id:
            to_user_id = conversation.from_user_id
        else:
            to_user_id = conversation.to_user_id

        form.save(conversation=conversation, user_id=current_user.id)

        # save the message in the recievers conversation
        old_conv = conversation
        conversation = Conversation.query.\
            filter(
                Conversation.user_id == to_user_id,
                Conversation.shared_id == conversation.shared_id
            ).first()

        # user deleted the conversation, start a new conversation with just
        # the recieving message
        if conversation is None:
            conversation = Conversation(
                subject=old_conv.subject,
                from_user_id=current_user.id,
                to_user=to_user_id,
                user_id=to_user_id,
                shared_id=old_conv.shared_id
            )
            conversation.save()

        form.save(conversation=conversation, user_id=current_user.id,
                  unread=True)
        conversation.to_user.invalidate_cache(permissions=False)

        return redirect(url_for("message.view_conversation",
                                conversation_id=old_conv.id))

    return render_template("message/conversation.html",
                           conversation=conversation, form=form)


@message.route("/new", methods=["POST", "GET"])
@login_required
def new_conversation():
    form = ConversationForm()
    to_user = request.args.get("to_user")

    message_count = Conversation.query.\
        filter(Conversation.user_id == current_user.id).\
        count()

    if message_count >= flaskbb_config["MESSAGE_QUOTA"]:
        flash(_("You cannot send any messages anymore because you have "
                "reached your message limit."), "danger")
        return redirect(url_for("message.inbox"))

    if request.method == "POST":
        if "save_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()

            shared_id = uuid.uuid4()

            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=current_user.id,
                      unread=False,
                      as_draft=True,
                      shared_id=shared_id)

            flash(_("Message saved."), "success")
            return redirect(url_for("message.drafts"))

        if "send_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()

            # this is the shared id between conversations because the messages
            # are saved on both ends
            shared_id = uuid.uuid4()

            # Save the message in the current users inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=current_user.id,
                      unread=False,
                      shared_id=shared_id)

            # Save the message in the recievers inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=to_user.id,
                      unread=True,
                      shared_id=shared_id)
            to_user.invalidate_cache(permissions=False)

            flash(_("Message sent."), "success")
            return redirect(url_for("message.sent"))
    else:
        form.to_user.data = to_user

    return render_template("message/message_form.html", form=form,
                           title=_("Compose Message"))


@message.route("/message/<int:message_id>/raw")
@login_required
def raw_message(message_id):
    message = Message.query.filter_by(id=message_id).first_or_404()

    # abort if the message was not the current_user's one or the one of the
    # recieved ones
    if not (message.conversation.from_user_id == current_user.id or
            message.conversation.to_user_id == current_user.id):
        abort(404)

    return format_quote(username=message.user.username,
                        content=message.message)


@message.route("/<int:conversation_id>/edit", methods=["POST", "GET"])
@login_required
def edit_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    if not conversation.draft:
        flash(_("You cannot edit a sent message."), "danger")
        return redirect(url_for("message.inbox"))

    form = ConversationForm()

    if request.method == "POST":
        if "save_message" in request.form:
            to_user = User.query.filter_by(username=form.to_user.data).first()

            conversation.draft = True
            conversation.to_user_id = to_user.id
            conversation.first_message.message = form.message.data
            conversation.save()

            flash(_("Message saved."), "success")
            return redirect(url_for("message.drafts"))

        if "send_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()
            # Save the message in the recievers inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=to_user.id,
                      unread=True,
                      shared_id=conversation.shared_id)

            # Move the message from ``Drafts`` to ``Sent``.
            conversation.draft = False
            conversation.to_user = to_user
            conversation.date_created = time_utcnow()
            conversation.save()

            flash(_("Message sent."), "success")
            return redirect(url_for("message.sent"))
    else:
        form.to_user.data = conversation.to_user.username
        form.subject.data = conversation.subject
        form.message.data = conversation.first_message.message

    return render_template("message/message_form.html", form=form,
                           title=_("Edit Message"))


@message.route("/<int:conversation_id>/move", methods=["POST"])
@login_required
def move_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    conversation.trash = True
    conversation.save()

    return redirect(url_for("message.inbox"))


@message.route("/<int:conversation_id>/restore", methods=["POST"])
@login_required
def restore_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    conversation.trash = False
    conversation.save()
    return redirect(url_for("message.inbox"))


@message.route("/<int:conversation_id>/delete", methods=["POST"])
@login_required
def delete_conversation(conversation_id):
    conversation = Conversation.query.filter_by(
        id=conversation_id,
        user_id=current_user.id
    ).first_or_404()

    conversation.delete()
    return redirect(url_for("message.inbox"))


@message.route("/sent")
@login_required
def sent():
    page = request.args.get('page', 1, type=int)

    conversations = Conversation.query.\
        filter(
            Conversation.id == Message.conversation_id,

flaskbb/user/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.user.views
    ~~~~~~~~~~~~~~~~~~

    The user view handles the user profile
    and the user settings from a signed in user.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask import Blueprint, flash, request
from flask_login import login_required, current_user
from flask_themes2 import get_themes_list
from flask_babelplus import gettext as _

from flaskbb.extensions import babel
from flaskbb.utils.helpers import render_template
from flaskbb.user.models import User
from flaskbb.user.forms import (ChangePasswordForm, ChangeEmailForm,
                                ChangeUserDetailsForm, GeneralSettingsForm)


user = Blueprint("user", __name__)


@user.route("/<username>")
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template("user/profile.html", user=user)


@user.route("/<username>/topics")
def view_all_topics(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    topics = user.all_topics(page, current_user)
    return render_template("user/all_topics.html", user=user, topics=topics)


@user.route("/<username>/posts")
def view_all_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.all_posts(page, current_user)
    return render_template("user/all_posts.html", user=user, posts=posts)


@user.route("/settings/general", methods=["POST", "GET"])
@login_required
def settings():
    form = GeneralSettingsForm()

    form.theme.choices = [(theme.identifier, theme.name)
                          for theme in get_themes_list()]

    form.language.choices = [(locale.language, locale.display_name)
                             for locale in babel.list_translations()]

    if form.validate_on_submit():
        current_user.theme = form.theme.data
        current_user.language = form.language.data
        current_user.save()

        flash(_("Settings updated."), "success")
    else:
        form.theme.data = current_user.theme
        form.language.data = current_user.language

    return render_template("user/general_settings.html", form=form)


@user.route("/settings/password", methods=["POST", "GET"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        current_user.save()

        flash(_("Password updated."), "success")
    return render_template("user/change_password.html", form=form)


@user.route("/settings/email", methods=["POST", "GET"])
@login_required
def change_email():
    form = ChangeEmailForm(current_user)
    if form.validate_on_submit():
        current_user.email = form.new_email.data
        current_user.save()

        flash(_("Email address updated."), "success")
    return render_template("user/change_email.html", form=form)


@user.route("/settings/user-details", methods=["POST", "GET"])
@login_required
def change_user_details():
    form = ChangeUserDetailsForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()

        flash(_("User details updated."), "success")

    return render_template("user/change_user_details.html", form=form)

flaskbb/templates/confirm_dialog.html
<div class="modal fade confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="confirmModalLabel">{% trans %}Are you sure?{% endtrans %}</h4>
            </div>
            <div class="modal-body">
                <p>{% trans %}Are you sure that you want to perform this action? This action is irreversible.{% endtrans %}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans %}Cancel{% endtrans %}</button>
                <button type="button" class="btn btn-danger btn-ok confirmBtn">{% trans %}Yes{% endtrans %}</button>
            </div>
        </div>
    </div>
</div>

flaskbb/templates/editor_help.html
<!-- Modal -->
<div class="modal fade" id="editor-help" tabindex="-1" role="dialog" aria-labelledby="editor-help">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="editor-help">Editor Cheatsheet</h4>
            </div>
            <div class="modal-body">
                <div class="cheatsheet">
                    <h2>Emojis</h2>
                    <div class="emojis">
                        A full list of available emojis can be found <a href="http://www.emoji-cheat-sheet.com/">here</a>.
                    </div>

                    <h2>Typography</h2>
                    <div class="typography">
                        <span >
                            # Header1 <br>
                            ## Header2 <br>
                        </span>
                        <span>
                            * Unordered item1 <br>
                            * Unordered item2 <br>
                        </span>
                        <span>
                            1. Ordered item1 <br>
                            2. Ordered item2 <br>
                        </span>
                    </div>
                    <p class="text-center" style="margin-top: 1em;">*<em>Emphasized text</em>*</p>
                    <p class="text-center">**<strong>Bold Text</strong>**</p>
                    <p class="text-center">*** (Horizontal rule)</p>
                    <p class="text-center">> Blockquote</p>
                    <h2>Links</h2>
                    <p class="text-center">[Google](http://www.google.com)</p>
                    <p class="text-center">[Google](http://www.google.com "Google")</p>
                    <p class="text-center">&hellip;</p>
                    <p class="text-center">![Img Description](/path/to/kittens.jpg)</p>
                    <p class="text-center">[![Description](http://kittens.com/kitty.jpg)](http://google.com)</p>
                    <h2>Code</h2>
                    <div class="code-hints" style="margin-top: 2em;">
                        <div class="code-example">
                            <span>
                            ```python <br>
                            print "Hello world"<br>
                            ```
                            </span>

                            <span class="markup">{{ '```python\r print "Hello World"\n```' | markup }}</span>
                        </div>
                    </div>
                    <p class="credit text-center" style="bottom: 10px; position: absolute; left: 0; right: 0; margin: 0 auto">
                        <small>For a more detailed info visit the <a href="http://daringfireball.net/projects/markdown/basics">official Markdown website</a></small>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

flaskbb/templates/flashed_messages.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                {% set icon = 'glyphicon glyphicon-exclamation-sign' %}
            {% elif category == 'success' %}
                {% set icon = 'glyphicon glyphicon-ok-sign' %}
            {% else %}
                {% set icon = 'glyphicon glyphicon-info-sign' %}
            {% endif %}
            <div class="alert alert-{{ category }}">
                <span class="{{ icon }}"></span>&nbsp;
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

flaskbb/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="FlaskBB is a forum software written in Flask">
        <meta name="author" content="FlaskBB Team">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

        <title>
        {% block title %}
            {%- if not page_title -%}
                {{ flaskbb_config["PROJECT_TITLE"] }} - {{ flaskbb_config["PROJECT_SUBTITLE"] }}
            {%- else -%}
                {{ page_title }} - {{ flaskbb_config["PROJECT_TITLE"] }}
            {%- endif -%}
        {% endblock %}
        </title>

        {% block stylesheets %}
        <!-- syntax highlighting -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/pygments.css') }}">
        <!-- bootstrap & aurora theme -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <!-- lato font -->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        {% endblock %}

        {# for extra stylesheets. e.q. a template has to add something #}
        {% block css %}
        {% endblock %}

        {# for various extra things #}
        {% block head_extra %}
        {% endblock %}
    </head>

    <body>

        <!-- main forum layout -->
        <div class="flaskbb-layout">
            <div class="container">

                <!-- forum header - place for the project title and subtitle -->
                {% block header %}
                <div class="flaskbb-header">
                    <div class="flaskbb-meta">
                        <div class="flaskbb-title">{{ flaskbb_config["PROJECT_TITLE"] }}</div>
                        <div class="flaskbb-subtitle">{{ flaskbb_config["PROJECT_SUBTITLE"] }}</div>
                    </div>
                </div>
                {% endblock %}

                <!-- forum menu - contains all the navigation items -->
                {% block navigation %}
                <div class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                    </div>

                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <!-- navbar left -->
                        <ul class="nav navbar-nav forum-nav">
                            {%- from theme("macros.html") import is_active, topnav with context -%}
                            {{ emit_event("before-first-navigation-element") }}

                            {{ topnav(endpoint='forum.index', name=_('Forum'), icon='fa fa-comment', active=active_forum_nav) }}
                            {{ topnav(endpoint='forum.memberlist', name=_('Memberlist'), icon='fa fa-user') }}
                            {{ topnav(endpoint='forum.search', name=_('Search'), icon='fa fa-search') }}

                            {{ emit_event("after-last-navigation-element") }}
                        </ul>

                        <!-- navbar right -->
                        <ul class="nav navbar-nav navbar-right">

                            {% if current_user and current_user.is_authenticated %}
                            <!-- Inbox -->
                            <li class="dropdown {{ is_active('message.inbox') }}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="fa fa-envelope fa-fw"></span> {% trans %}Inbox{% endtrans %}
                                    {% if current_user.unread_count > 0 %}
                                    <span class="label label-danger">{{ current_user.unread_count }}</span>
                                    {% else %}
                                    <span class="label label-info">{{ current_user.unread_count }}</span>
                                    {% endif %}
                                </a>
                                <ul class="dropdown-menu dropdown-messages">
                                    {% for message in current_user.unread_messages %}
                                    <li>
                                        <a href="{{ url_for('message.view_conversation', conversation_id=message.id) }}">
                                            <div>
                                                <span class="author-name">{{ message.from_user.username }}</span> <span class="pull-right text-muted">{{ message.last_message.date_created|time_since }}</span>
                                                <div class="message-subject">{{ message.subject }}</div>
                                            </div>
                                        </a>
                                    </li>
                                    {% else %}
                                    <li><a href="#">No unread messages.</a></li>
                                    {% endfor %}
                                    <li class="divider"></li>
                                    <li><a href="{{ url_for('message.inbox') }}"><span class="fa fa-envelope fa-fw"></span> {% trans %}Inbox{% endtrans %}</a></li>
                                    <li><a href="{{ url_for('message.new_conversation') }}"><span class="fa fa-pencil fa-fw"></span> {% trans %}New Message{% endtrans %}</a></li>
                                </ul>
                            </li>

                            <!-- User Menu -->
                            <li>
                                <div class="btn-group navbar-btn user-btn">
                                    <a class="btn btn-primary" href="{{ url_for('user.profile', username=current_user.username) }}">
                                        <span class="fa fa-user fa-fw"></span> {{ current_user.username }}
                                    </a>
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{{ url_for('forum.topictracker') }}"><span class="fa fa-book fa-fw"></span> {% trans %}Topic Tracker{% endtrans %}</a></li>
                                        <li class="divider"></li>

                                        <li><a href="{{ url_for('user.settings') }}"><span class="fa fa-cogs fa-fw"></span> {% trans %}Settings{% endtrans %}</a></li>
                                        {% if current_user|is_admin_or_moderator %}
                                        <li><a href="{{ url_for('management.overview') }}"><span class="fa fa-cog fa-fw"></span> {% trans %}Management{% endtrans %}</a></li>
                                        <li class="divider"></li>
                                        {% endif %}

                                        <li><a href="{{ url_for('auth.logout') }}"><span class="fa fa-power-off fa-fw"></span> {% trans %}Logout{% endtrans %}</a></li>
                                    </ul>
                                </div>
                            </li>
                            {% else %}
                            <!-- Not logged in - Login/Register -->
                            <li>
                                <div class="btn-group navbar-btn user-btn">
                                    <a class="btn btn-primary" href="{{ url_for('auth.login') }}">
                                        <span class="fa fa-user fa-fw"></span> {% trans %}Login{% endtrans %}
                                    </a>
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                                    <ul class="dropdown-menu" role="menu">
                                        {% if flaskbb_config["REGISTRATION_ENABLED"] %}
                                        <li><a href="{{ url_for('auth.register') }}"><span class="fa fa-user-plus fa-fw"></span> {% trans %}Register{% endtrans %}</a></li>
                                        {% endif %}
                                        <li><a href="{{ url_for('auth.forgot_password') }}"><span class="fa fa-undo fa-fw"></span> {% trans %}Reset Password{% endtrans %}</a></li>
                                    </ul>
                                </div>
                            </li>
                            {% endif %}

                        </ul> <!-- end navbar right -->
                    </div> <!-- end navbar-collapse -->
                </div> <!-- end navbar -->
                {% endblock %}

                <!-- Place for all the (flashed) messages -->
                {% block messages %}
                <div id="flashed-messages">
                    {% include theme('flashed_messages.html') %}
                </div>
                {% endblock %}

                <!-- the actual content block -->
                {% block content %}
                {% endblock %}
            </div> <!-- end container -->

            <!-- the forum footer -->
            {% block footer %}
            <footer class="flaskbb-footer">
                <div class="container">
                    <p class="text-muted pull-right">powered by <a href="https://flaskbb.org">FlaskBB</a></p>
                    <p class="text-muted pull-left">&copy; 2013 - 2017 <a href="https://flaskbb.org">FlaskBB Team</a></p>
                </div>
            </footer>
            {% endblock %}

        </div> <!-- end flaskbb-layout -->

        {% block javascript %}
        <!-- jquery and bootstrap and flaskbb.js -->
        <script src="{{ url_for('static', filename='js/scripts.min.js') }}"></script>
        {% endblock %}

        {# for extra scripts in other templates. #}
        {% block scripts %}
        {% endblock %}
    </body>
</html>