flaskbb/forum/forms.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.forms
    ~~~~~~~~~~~~~~~~~~~

    It provides the forms that are needed for the forum views.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask_wtf import FlaskForm
from wtforms import (TextAreaField, StringField, SelectMultipleField,
                     BooleanField, SubmitField)
from wtforms.validators import DataRequired, Optional, Length
from flask_babelplus import lazy_gettext as _

from flaskbb.forum.models import Topic, Post, Report, Forum
from flaskbb.user.models import User


class QuickreplyForm(FlaskForm):
    content = TextAreaField(_("Quick reply"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    submit = SubmitField(_("Reply"))

    def save(self, user, topic):
        post = Post(content=self.content.data)
        return post.save(user=user, topic=topic)


class ReplyForm(FlaskForm):
    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Reply"))
    preview = SubmitField(_("Preview"))

    def save(self, user, topic):
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return post.save(user=user, topic=topic)


class NewTopicForm(ReplyForm):
    title = StringField(_("Topic title"), validators=[
        DataRequired(message=_("Please choose a title for your topic."))])

    content = TextAreaField(_("Content"), validators=[
        DataRequired(message=_("You cannot post a reply without content."))])

    track_topic = BooleanField(_("Track this topic"), default=False,
                               validators=[Optional()])

    submit = SubmitField(_("Post Topic"))
    preview = SubmitField(_("Preview"))

    def save(self, user, forum):
        topic = Topic(title=self.title.data)
        post = Post(content=self.content.data)

        if self.track_topic.data:
            user.track_topic(topic)
        return topic.save(user=user, forum=forum, post=post)


class ReportForm(FlaskForm):
    reason = TextAreaField(_("Reason"), validators=[
        DataRequired(message=_("What is the reason for reporting this post?"))
    ])

    submit = SubmitField(_("Report post"))

    def save(self, user, post):
        report = Report(reason=self.reason.data)
        return report.save(post=post, user=user)


class UserSearchForm(FlaskForm):
    search_query = StringField(_("Search"), validators=[
        Optional(), Length(min=3, max=50)
    ])

    submit = SubmitField(_("Search"))

    def get_results(self):
        query = self.search_query.data
        return User.query.whooshee_search(query)


class SearchPageForm(FlaskForm):
    search_query = StringField(_("Criteria"), validators=[
        DataRequired(), Length(min=3, max=50)])

    search_types = SelectMultipleField(_("Content"), validators=[
        DataRequired()], choices=[('post', _('Post')), ('topic', _('Topic')),
                                  ('forum', _('Forum')), ('user', _('Users'))])

    submit = SubmitField(_("Search"))

    def get_results(self):
        # Because the DB is not yet initialized when this form is loaded,
        # the query objects cannot be instantiated in the class itself
        search_actions = {
            'post': Post.query.whooshee_search,
            'topic': Topic.query.whooshee_search,
            'forum': Forum.query.whooshee_search,
            'user': User.query.whooshee_search
        }

        query = self.search_query.data
        types = self.search_types.data
        results = {}

        for search_type in search_actions.keys():
            if search_type in types:
                results[search_type] = search_actions[search_type](query)

        return results

flaskbb/forum/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.views
    ~~~~~~~~~~~~~~~~~~~

    This module handles the forum logic like creating and viewing
    topics and posts.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import math
from sqlalchemy import asc, desc
from flask import (Blueprint, redirect, url_for, current_app, request, flash,
                   abort)
from flask_login import login_required, current_user
from flask_babelplus import gettext as _
from flask_allows import Permission, And

from flaskbb.extensions import db, allows
from flaskbb.utils.settings import flaskbb_config
from flaskbb.utils.helpers import (get_online_users, time_diff, time_utcnow,
                                   format_quote, render_template,
                                   do_topic_action)
from flaskbb.utils.requirements import (CanAccessForum, CanAccessTopic,
                                        CanDeletePost, CanDeleteTopic,
                                        CanEditPost, CanPostReply,
                                        CanPostTopic,
                                        IsAtleastModeratorInForum)
from flaskbb.forum.models import (Category, Forum, Topic, Post, ForumsRead,
                                  TopicsRead)
from flaskbb.forum.forms import (NewTopicForm, QuickreplyForm, ReplyForm,
                                 ReportForm, SearchPageForm, UserSearchForm)
from flaskbb.user.models import User

forum = Blueprint("forum", __name__)


@forum.route("/")
def index():
    categories = Category.get_all(user=current_user)

    # Fetch a few stats about the forum
    user_count = User.query.count()
    topic_count = Topic.query.count()
    post_count = Post.query.count()
    newest_user = User.query.order_by(User.id.desc()).first()

    # Check if we use redis or not
    if not current_app.config["REDIS_ENABLED"]:
        online_users = User.query.filter(User.lastseen >= time_diff()).count()

        # Because we do not have server side sessions, we cannot check if there
        # are online guests
        online_guests = None
    else:
        online_users = len(get_online_users())
        online_guests = len(get_online_users(guest=True))

    return render_template("forum/index.html",
                           categories=categories,
                           user_count=user_count,
                           topic_count=topic_count,
                           post_count=post_count,
                           newest_user=newest_user,
                           online_users=online_users,
                           online_guests=online_guests)


@forum.route("/category/<int:category_id>")
@forum.route("/category/<int:category_id>-<slug>")
def view_category(category_id, slug=None):
    category, forums = Category.\
        get_forums(category_id=category_id, user=current_user)

    return render_template("forum/category.html", forums=forums,
                           category=category)


@forum.route("/forum/<int:forum_id>")
@forum.route("/forum/<int:forum_id>-<slug>")
@allows.requires(CanAccessForum())
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(
        forum_id=forum_id, user=current_user
    )

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(
        forum_id=forum_instance.id, user=current_user, page=page,
        per_page=flaskbb_config["TOPICS_PER_PAGE"]
    )

    return render_template(
        "forum/forum.html", forum=forum_instance,
        topics=topics, forumsread=forumsread,
    )


@forum.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@forum.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
@allows.requires(CanAccessTopic())
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    # Fetch some information about the topic
    topic = Topic.get_topic(topic_id=topic_id, user=current_user)

    # Count the topic views
    topic.views += 1
    topic.save()

    # fetch the posts in the topic
    posts = Post.query.\
        outerjoin(User, Post.user_id == User.id).\
        filter(Post.topic_id == topic.id).\
        add_entity(User).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Abort if there are no posts on this page
    if len(posts.items) == 0:
        abort(404)

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated:
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)

    form = None
    if Permission(CanPostReply):
        form = QuickreplyForm()
        if form.validate_on_submit():
            post = form.save(current_user, topic)
            return view_post(post.id)

    return render_template("forum/topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)


@forum.route("/post/<int:post_id>")
def view_post(post_id):
    """Redirects to a post in a topic."""
    post = Post.query.filter_by(id=post_id).first_or_404()
    post_in_topic = Post.query.\
        filter(Post.topic_id == post.topic_id,
               Post.id <= post_id).\
        order_by(Post.id.asc()).\
        count()
    page = math.ceil(post_in_topic / float(flaskbb_config['POSTS_PER_PAGE']))

    return redirect(post.topic.url + "?page=%d#pid%s" % (page, post.id))


@forum.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@forum.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])
@login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    if not Permission(CanPostTopic):
        flash(_("You do not have the permissions to create a new topic."),
              "danger")
        return redirect(forum_instance.url)

    form = NewTopicForm()
    if request.method == "POST":
        if "preview" in request.form and form.validate():
            return render_template(
                "forum/new_topic.html", forum=forum_instance,
                form=form, preview=form.content.data
            )
        if "submit" in request.form and form.validate():
            topic = form.save(current_user, forum_instance)
            # redirect to the new topic
            return redirect(url_for('forum.view_topic', topic_id=topic.id))

    return render_template(
        "forum/new_topic.html", forum=forum_instance, form=form
    )


@forum.route("/topic/<int:topic_id>/delete", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/delete", methods=["POST"])
@login_required
def delete_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(CanDeleteTopic):
        flash(_("You do not have the permissions to delete this topic."),
              "danger")
        return redirect(topic.forum.url)

    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    return redirect(url_for("forum.view_forum", forum_id=topic.forum_id))


@forum.route("/topic/<int:topic_id>/lock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/lock", methods=["POST"])
@login_required
def lock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to lock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/unlock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/unlock", methods=["POST"])
@login_required
def unlock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to unlock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/highlight", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/highlight", methods=["POST"])
@login_required
def highlight_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to highlight this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/trivialize", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/trivialize", methods=["POST"])
@login_required
def trivialize_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # Unlock is basically the same as lock
    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to trivialize this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = False
    topic.save()
    return redirect(topic.url)


@forum.route("/forum/<int:forum_id>/edit", methods=["POST", "GET"])
@forum.route("/forum/<int:forum_id>-<slug>/edit", methods=["POST", "GET"])
@login_required
def manage_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id,
                                                 user=current_user)

flaskbb/user/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.user.views
    ~~~~~~~~~~~~~~~~~~

    The user view handles the user profile
    and the user settings from a signed in user.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask import Blueprint, flash, request
from flask_login import login_required, current_user
from flask_themes2 import get_themes_list
from flask_babelplus import gettext as _

from flaskbb.extensions import babel
from flaskbb.utils.helpers import render_template
from flaskbb.user.models import User
from flaskbb.user.forms import (ChangePasswordForm, ChangeEmailForm,
                                ChangeUserDetailsForm, GeneralSettingsForm)


user = Blueprint("user", __name__)


@user.route("/<username>")
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template("user/profile.html", user=user)


@user.route("/<username>/topics")
def view_all_topics(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    topics = user.all_topics(page, current_user)
    return render_template("user/all_topics.html", user=user, topics=topics)


@user.route("/<username>/posts")
def view_all_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.all_posts(page, current_user)
    return render_template("user/all_posts.html", user=user, posts=posts)


@user.route("/settings/general", methods=["POST", "GET"])
@login_required
def settings():
    form = GeneralSettingsForm()

    form.theme.choices = [(theme.identifier, theme.name)
                          for theme in get_themes_list()]

    form.language.choices = [(locale.language, locale.display_name)
                             for locale in babel.list_translations()]

    if form.validate_on_submit():
        current_user.theme = form.theme.data
        current_user.language = form.language.data
        current_user.save()

        flash(_("Settings updated."), "success")
    else:
        form.theme.data = current_user.theme
        form.language.data = current_user.language

    return render_template("user/general_settings.html", form=form)


@user.route("/settings/password", methods=["POST", "GET"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        current_user.save()

        flash(_("Password updated."), "success")
    return render_template("user/change_password.html", form=form)


@user.route("/settings/email", methods=["POST", "GET"])
@login_required
def change_email():
    form = ChangeEmailForm(current_user)
    if form.validate_on_submit():
        current_user.email = form.new_email.data
        current_user.save()

        flash(_("Email address updated."), "success")
    return render_template("user/change_email.html", form=form)


@user.route("/settings/user-details", methods=["POST", "GET"])
@login_required
def change_user_details():
    form = ChangeUserDetailsForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()

        flash(_("User details updated."), "success")

    return render_template("user/change_user_details.html", form=form)

flaskbb/templates/forum/category.html
{% set page_title = category.title %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}
{% block content %}

<div class="index-view">
    <ol class="breadcrumb flaskbb-breadcrumb">
        <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
        <li class="active">{{ category.title }}</li>
    </ol>

    {% include theme("forum/category_layout.html") %}
</div>

{% endblock %}

flaskbb/templates/forum/forum.html
{% set page_title = forum.title %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}
{% block content %}
{% from theme('macros.html') import render_pagination, topic_pages %}

<div class="forum-view">
    <ol class="breadcrumb flaskbb-breadcrumb">
        <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
        <li><a href="{{ forum.category.url }}">{{ forum.category.title }}</a></li>
        <li class="active">{{ forum.title }}</li>
    </ol>

    <div class="row controls-row">
        <div class="pull-left">
            {{ render_pagination(topics, forum.url) }}
        </div> <!-- end span pagination -->

        {% if current_user|post_topic(forum) %}
        <div class="pull-right">
            <form class="inline-form" method="post" action="{{ url_for('forum.markread', forum_id=forum.id, slug=forum.slug) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button class="btn btn-default">
                    <span class="fa fa-check fa-fw"></span> {% trans %}Mark as Read{% endtrans %}
                </button>
            </form>

            {% if forum.locked %}
            <span class="btn btn-primary">
                <span class="fa fa-lock fa-fw"></span> {% trans %}Locked{% endtrans %}
            </span>
            {% else %}
            <a href="{{ url_for('forum.new_topic', forum_id=forum.id, slug=forum.slug) }}" class="btn btn-primary">
                <span class="fa fa-pencil fa-fw"></span> {% trans %}New Topic{% endtrans %}
            </a>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="panel forum-panel">
        <div class="panel-heading forum-head">
            <a href="{{ forum.url }}">{{ forum.title }}</a>
        </div>

        <div class="panel-body forum-body">
            <div class="forum-meta">
                <div class="col-md-5 col-sm-5 col-xs-8 topic-name">{% trans %}Topic{% endtrans %}</div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">{% trans %}Posts{% endtrans %}</div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">{% trans %}Views{% endtrans %}</div>
                <div class="col-md-3 col-sm-3 col-xs-4 topic-last-post">{% trans %}Last Post{% endtrans %}</div>
            </div>

            {% for topic, topicread in topics.items %}
            <div class="row forum-row hover clearfix">

                <div class="col-md-5 col-sm-5 col-xs-8 topic-info">
                    <div class="row">
                        <div class="col-md-1 col-sm-2 col-xs-2 topic-status">
                        {% if topic.locked %}
                            <span class="fa fa-lock fa-fw topic-locked"></span>
                        {% elif topic.important %}
                            {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                                <span class="fa fa-star fa-fw topic-starred-unread"></span>
                            {% else %}
                                <span class="fa fa-star-o fa-fw topic-starred-read"></span>
                            {% endif %}
                        {% else %}
                            {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                                <span class="fa fa-comment fa-fw topic-unread"></span>
                            {% else %}
                                <span class="fa fa-comment-o fa-fw topic-read"></span>
                            {% endif %}
                        {% endif %}
                        </div>
                        <div class="col-md-11 col-sm-10 col-xs-10">
                            <div class="topic-name">
                                <a href="{{ topic.first_unread(topicread, current_user, forumsread) }}">{{ topic.title }}</a>
                                <!-- Topic Pagination -->
                                <span class="topic-pages">{{ topic_pages(topic, flaskbb_config["POSTS_PER_PAGE"]) }}</span>
                            </div>

                            <div class="topic-author">
                                {% trans %}by{% endtrans %}
                                {% if topic.user_id %}
                                 <a href="{{ topic.user.url }}">{{ topic.user.username }}</a>
                                {% else %}
                                {{ topic.username }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">
                    {{ topic.post_count }}
                </div>

                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">
                    {{ topic.views }}
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4 topic-last-post">
                    <a href="{{ topic.last_post.url }}">{{ topic.last_post.date_created|time_since }}</a><br />

                    <div class="topic-author">
                        {% trans %}by{% endtrans %}
                        {% if topic.last_post.user_id %}
                        <a href="{{ topic.last_post.user.url }}">{{ topic.last_post.user.username }}</a>
                        {% else %}
                        {{ topic.last_post.username }}
                        {% endif %}
                    </div>
                </div>

            </div>  <!-- end forum-row -->
            {% else %}
            <div class="row forum-row clearfix">
                <div class="col-md-12 col-sm-12 co-xs-12">
                    {% trans %}No Topics.{% endtrans %}
                </div>
            </div> <!-- end forum-row -->
            {% endfor %}
        </div>
    </div>

    {% if current_user|can_moderate(forum) %}
    <div class="row controls-row">
        <a class="btn btn-default" href="{{ url_for('forum.manage_forum', forum_id=forum.id, slug=forum.slug) }}">
            <span class="fa fa-tasks fa-fw"></span> {% trans %}Moderation Mode{% endtrans %}
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}

flaskbb/templates/forum/new_topic.html
{% set page_title = _("New Topic") %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}

{% block content %}
{% from theme("macros.html") import render_field, render_submit_field, render_quickreply %}

<div class="page-view">
    <ol class="breadcrumb flaskbb-breadcrumb">
        <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
        <li><a href="{{ forum.url }}">{{ forum.title }}</a></li>
        <li class="active">{% trans %}New Topic{% endtrans %}</li>
    </ol>


    <form class="form-horizontal" role="form" method="post">
        {{ form.hidden_tag() }}
        <div class="panel page-panel">
            <div class="panel-heading page-head">
                {% trans %}New Topic{% endtrans %}
            </div>

            <div class="panel-body page-body">
                {{ form.hidden_tag() }}
                <div class="col-md-12 col-sm-12 col-xs-12">

                    {{ render_field(form.title, div_class="col-md-12 col-sm-12 col-xs-12") }}

                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="editor-box">
                                <div class="editor">
                                    {{ render_quickreply(form.content, div_class="new-message", rows=7, cols=75, placeholder="", **{'data-provide': 'markdown', 'data-autofocus': 'false', 'class': 'flaskbb-editor'}) }}
                                </div>
                                <div class="editor-submit">
                                    {{ render_submit_field(form.submit, input_class="btn btn-success pull-right") }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include theme('editor_help.html') %}
    </form>
</div>
{% endblock %}

flaskbb/templates/forum/topic_controls.html
<div class="row controls-row">
    <div class ="col-md-6 col-sm-6 col-xs-12 controls-col">
        <div class="pull-left">
            {{ render_pagination(posts, topic.url) }}
        </div>
    </div> <!-- end span pagination -->

{% if current_user.is_authenticated %}
    <div class="col-md-6 col-sm-6 col-xs-12 controls-col">
        <div class="pull-right">
            {% if current_user|can_moderate(topic.forum) or current_user|delete_topic(topic)%}
            <!-- Moderation buttons -->
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="fa fa-bars fa-fw" aria-hidden="true"></span> {% trans %}Moderate{% endtrans %} <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">

                {% if current_user|delete_topic(topic) %}
                <li>
                    <form class="inline-form" method="post" action="{{ url_for('forum.delete_topic', topic_id=topic.id, slug=topic.slug) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button class="btn btn-link">
                            <span class="fa fa-trash-o fa-fw"></span> {% trans %}Delete Topic{% endtrans %}
                        </button>
                    </form>
                </li>
                {% endif %}

                {% if current_user|can_moderate(topic.forum) %}
                    {% if not topic.locked %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('forum.lock_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-lock fa-fw"></span> {% trans %}Lock Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% else %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('forum.unlock_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-unlock fa-fw"></span> {% trans %}Unlock Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% endif %}

                    {% if not topic.important %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('forum.highlight_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-star fa-fw"></span> {% trans %}Highlight Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% else %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('forum.trivialize_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-star-o fa-fw"></span> {% trans %}Trivialize Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% endif %}
                {% endif %}
                </ul>
            </div>
            <!-- end Moderation buttons -->
            {% endif %}

            {% if current_user.is_tracking_topic(topic) %}
            <form class="inline-form" method="post" action="{{ url_for('forum.untrack_topic', topic_id=topic.id, slug=topic.slug) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button class="btn btn-default">
                    <span class="fa fa-tag fa-fw" aria-hidden="true"></span> {% trans %}Untrack Topic{% endtrans %}
                </button>
            </form>
            {% else %}
            <form class="inline-form" method="post" action="{{ url_for('forum.track_topic', topic_id=topic.id, slug=topic.slug) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button class="btn btn-default">
                    <span class="fa fa-tag fa-fw" aria-hidden="true"></span> {% trans %}Track Topic{% endtrans %}
                </button>
            </form>
            {% endif %}

            {% if current_user|post_reply(topic) %}
            <a href="{{ url_for('forum.new_post', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-primary">
                <span class="fa fa-pencil fa-fw"></span> {% trans %}Reply{% endtrans %}
            </a>
            {% else %}
            <div class="btn btn-primary"><span class="fa fa-lock fa-fw"></span> {% trans %}Locked{% endtrans %}</div>
            {% endif %}
        </div>
    </div>
{% endif %} {# end current_user.is_authenticated #}
</div>