flaskbb/user/forms.py
# -*- coding: utf-8 -*-
"""
    flaskbb.user.forms
    ~~~~~~~~~~~~~~~~~~

    It provides the forms that are needed for the user views.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, TextAreaField, SelectField,
                     ValidationError, SubmitField)
from wtforms.validators import (Length, DataRequired, InputRequired, Email,
                                EqualTo, Optional, URL)
from flask_babelplus import lazy_gettext as _

from flaskbb.user.models import User
from flaskbb.extensions import db
from flaskbb.utils.fields import BirthdayField
from flaskbb.utils.helpers import check_image


class GeneralSettingsForm(FlaskForm):
    # The choices for those fields will be generated in the user view
    # because we cannot access the current_app outside of the context
    language = SelectField(_("Language"))
    theme = SelectField(_("Theme"))

    submit = SubmitField(_("Save"))


class ChangeEmailForm(FlaskForm):
    old_email = StringField(_("Old email address"), validators=[
        DataRequired(message=_("A valid email address is required.")),
        Email(message=_("Invalid email address."))])

    new_email = StringField(_("New email address"), validators=[
        InputRequired(),
        EqualTo('confirm_new_email', message=_("Email addresses must match.")),
        Email(message=_("Invalid email address."))])

    confirm_new_email = StringField(_("Confirm email address"), validators=[
        Email(message=_("Invalid email address."))])

    submit = SubmitField(_("Save"))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        kwargs['obj'] = self.user
        super(ChangeEmailForm, self).__init__(*args, **kwargs)

    def validate_email(self, field):
        user = User.query.filter(db.and_(
                                 User.email.like(field.data),
                                 db.not_(User.id == self.user.id))).first()
        if user:
            raise ValidationError(_("This email address is already taken."))


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField(_("Password"), validators=[
        DataRequired(message=_("Please enter your password."))])

    new_password = PasswordField(_('New password'), validators=[
        InputRequired(),
        EqualTo('confirm_new_password', message=_('New passwords must match.'))
    ])

    confirm_new_password = PasswordField(_('Confirm new password'))

    submit = SubmitField(_("Save"))

    def validate_old_password(self, field):
        if not current_user.check_password(field.data):
            raise ValidationError(_("Old password is wrong."))


class ChangeUserDetailsForm(FlaskForm):
    birthday = BirthdayField(_("Birthday"), format="%d %m %Y", validators=[
        Optional()])

    gender = SelectField(_("Gender"), default="None", choices=[
        ("None", ""),
        ("Male", _("Male")),
        ("Female", _("Female"))])

    location = StringField(_("Location"), validators=[
        Optional()])

    website = StringField(_("Website"), validators=[
        Optional(), URL()])

    avatar = StringField(_("Avatar"), validators=[
        Optional(), URL()])

    signature = TextAreaField(_("Forum Signature"), validators=[
        Optional()])

    notes = TextAreaField(_("Notes"), validators=[
        Optional(), Length(min=0, max=5000)])

    submit = SubmitField(_("Save"))

    def validate_birthday(self, field):
        if field.data is None:
            return True

    def validate_avatar(self, field):
        if field.data is not None:
            error, status = check_image(field.data)
            if error is not None:
                raise ValidationError(error)
            return status

flaskbb/forum/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.views
    ~~~~~~~~~~~~~~~~~~~

    This module handles the forum logic like creating and viewing
    topics and posts.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import math
from sqlalchemy import asc, desc
from flask import (Blueprint, redirect, url_for, current_app, request, flash,
                   abort)
from flask_login import login_required, current_user
from flask_babelplus import gettext as _
from flask_allows import Permission, And

from flaskbb.extensions import db, allows
from flaskbb.utils.settings import flaskbb_config
from flaskbb.utils.helpers import (get_online_users, time_diff, time_utcnow,
                                   format_quote, render_template,
                                   do_topic_action)
from flaskbb.utils.requirements import (CanAccessForum, CanAccessTopic,
                                        CanDeletePost, CanDeleteTopic,
                                        CanEditPost, CanPostReply,
                                        CanPostTopic,
                                        IsAtleastModeratorInForum)
from flaskbb.forum.models import (Category, Forum, Topic, Post, ForumsRead,
                                  TopicsRead)
from flaskbb.forum.forms import (NewTopicForm, QuickreplyForm, ReplyForm,
                                 ReportForm, SearchPageForm, UserSearchForm)
from flaskbb.user.models import User

forum = Blueprint("forum", __name__)


@forum.route("/")
def index():
    categories = Category.get_all(user=current_user)

    # Fetch a few stats about the forum
    user_count = User.query.count()
    topic_count = Topic.query.count()
    post_count = Post.query.count()
    newest_user = User.query.order_by(User.id.desc()).first()

    # Check if we use redis or not
    if not current_app.config["REDIS_ENABLED"]:
        online_users = User.query.filter(User.lastseen >= time_diff()).count()

        # Because we do not have server side sessions, we cannot check if there
        # are online guests
        online_guests = None
    else:
        online_users = len(get_online_users())
        online_guests = len(get_online_users(guest=True))

    return render_template("forum/index.html",
                           categories=categories,
                           user_count=user_count,
                           topic_count=topic_count,
                           post_count=post_count,
                           newest_user=newest_user,
                           online_users=online_users,
                           online_guests=online_guests)


@forum.route("/category/<int:category_id>")
@forum.route("/category/<int:category_id>-<slug>")
def view_category(category_id, slug=None):
    category, forums = Category.\
        get_forums(category_id=category_id, user=current_user)

    return render_template("forum/category.html", forums=forums,
                           category=category)


@forum.route("/forum/<int:forum_id>")
@forum.route("/forum/<int:forum_id>-<slug>")
@allows.requires(CanAccessForum())
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(
        forum_id=forum_id, user=current_user
    )

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(
        forum_id=forum_instance.id, user=current_user, page=page,
        per_page=flaskbb_config["TOPICS_PER_PAGE"]
    )

    return render_template(
        "forum/forum.html", forum=forum_instance,
        topics=topics, forumsread=forumsread,
    )


@forum.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@forum.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
@allows.requires(CanAccessTopic())
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    # Fetch some information about the topic
    topic = Topic.get_topic(topic_id=topic_id, user=current_user)

    # Count the topic views
    topic.views += 1
    topic.save()

    # fetch the posts in the topic
    posts = Post.query.\
        outerjoin(User, Post.user_id == User.id).\
        filter(Post.topic_id == topic.id).\
        add_entity(User).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Abort if there are no posts on this page
    if len(posts.items) == 0:
        abort(404)

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated:
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)

    form = None
    if Permission(CanPostReply):
        form = QuickreplyForm()
        if form.validate_on_submit():
            post = form.save(current_user, topic)
            return view_post(post.id)

    return render_template("forum/topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)


@forum.route("/post/<int:post_id>")
def view_post(post_id):
    """Redirects to a post in a topic."""
    post = Post.query.filter_by(id=post_id).first_or_404()
    post_in_topic = Post.query.\
        filter(Post.topic_id == post.topic_id,
               Post.id <= post_id).\
        order_by(Post.id.asc()).\
        count()
    page = math.ceil(post_in_topic / float(flaskbb_config['POSTS_PER_PAGE']))

    return redirect(post.topic.url + "?page=%d#pid%s" % (page, post.id))


@forum.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@forum.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])
@login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    if not Permission(CanPostTopic):
        flash(_("You do not have the permissions to create a new topic."),
              "danger")
        return redirect(forum_instance.url)

    form = NewTopicForm()
    if request.method == "POST":
        if "preview" in request.form and form.validate():
            return render_template(
                "forum/new_topic.html", forum=forum_instance,
                form=form, preview=form.content.data
            )
        if "submit" in request.form and form.validate():
            topic = form.save(current_user, forum_instance)
            # redirect to the new topic
            return redirect(url_for('forum.view_topic', topic_id=topic.id))

    return render_template(
        "forum/new_topic.html", forum=forum_instance, form=form
    )


@forum.route("/topic/<int:topic_id>/delete", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/delete", methods=["POST"])
@login_required
def delete_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(CanDeleteTopic):
        flash(_("You do not have the permissions to delete this topic."),
              "danger")
        return redirect(topic.forum.url)

    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    return redirect(url_for("forum.view_forum", forum_id=topic.forum_id))


@forum.route("/topic/<int:topic_id>/lock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/lock", methods=["POST"])
@login_required
def lock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to lock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/unlock", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/unlock", methods=["POST"])
@login_required
def unlock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to unlock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/highlight", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/highlight", methods=["POST"])
@login_required
def highlight_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to highlight this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/trivialize", methods=["POST"])
@forum.route("/topic/<int:topic_id>-<slug>/trivialize", methods=["POST"])
@login_required
def trivialize_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # Unlock is basically the same as lock
    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to trivialize this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = False
    topic.save()
    return redirect(topic.url)


@forum.route("/forum/<int:forum_id>/edit", methods=["POST", "GET"])
@forum.route("/forum/<int:forum_id>-<slug>/edit", methods=["POST", "GET"])
@login_required
def manage_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id,
                                                 user=current_user)

flaskbb/user/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.user.views
    ~~~~~~~~~~~~~~~~~~

    The user view handles the user profile
    and the user settings from a signed in user.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from flask import Blueprint, flash, request
from flask_login import login_required, current_user
from flask_themes2 import get_themes_list
from flask_babelplus import gettext as _

from flaskbb.extensions import babel
from flaskbb.utils.helpers import render_template
from flaskbb.user.models import User
from flaskbb.user.forms import (ChangePasswordForm, ChangeEmailForm,
                                ChangeUserDetailsForm, GeneralSettingsForm)


user = Blueprint("user", __name__)


@user.route("/<username>")
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template("user/profile.html", user=user)


@user.route("/<username>/topics")
def view_all_topics(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    topics = user.all_topics(page, current_user)
    return render_template("user/all_topics.html", user=user, topics=topics)


@user.route("/<username>/posts")
def view_all_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.all_posts(page, current_user)
    return render_template("user/all_posts.html", user=user, posts=posts)


@user.route("/settings/general", methods=["POST", "GET"])
@login_required
def settings():
    form = GeneralSettingsForm()

    form.theme.choices = [(theme.identifier, theme.name)
                          for theme in get_themes_list()]

    form.language.choices = [(locale.language, locale.display_name)
                             for locale in babel.list_translations()]

    if form.validate_on_submit():
        current_user.theme = form.theme.data
        current_user.language = form.language.data
        current_user.save()

        flash(_("Settings updated."), "success")
    else:
        form.theme.data = current_user.theme
        form.language.data = current_user.language

    return render_template("user/general_settings.html", form=form)


@user.route("/settings/password", methods=["POST", "GET"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        current_user.save()

        flash(_("Password updated."), "success")
    return render_template("user/change_password.html", form=form)


@user.route("/settings/email", methods=["POST", "GET"])
@login_required
def change_email():
    form = ChangeEmailForm(current_user)
    if form.validate_on_submit():
        current_user.email = form.new_email.data
        current_user.save()

        flash(_("Email address updated."), "success")
    return render_template("user/change_email.html", form=form)


@user.route("/settings/user-details", methods=["POST", "GET"])
@login_required
def change_user_details():
    form = ChangeUserDetailsForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()

        flash(_("User details updated."), "success")

    return render_template("user/change_user_details.html", form=form)

flaskbb/templates/user/all_posts.html
{% extends theme("user/profile_layout.html") %}
{% from theme('macros.html') import render_pagination, topic_pages %}

{% block breadcrumb %}
<ul class="breadcrumb flaskbb-breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
    <li class="active">{% trans %}Posts{% endtrans %}</li>
</ul>
{% endblock %}

{% block profile_navigation %}
<ul class="nav profile-sidenav" id="profile-tabs" role="tablist">
    <li>
        <a href="{{ user.url }}">
            <span class="fa fa-home"></span> {% trans %}Overview{% endtrans %}
        </a>
    </li>
    {#
    <li>
        <a href="{{ user.url }}">
            <span class="fa fa-line-chart"></span> {% trans %}Statistics{% endtrans %}
        </a>
    </li>
    #}
    <li>
        <a href="{{ url_for('user.view_all_topics', username=user.username) }}">
            <span class="fa fa-comments"></span> {% trans %}Topics{% endtrans %}
        </a>
    </li>

    <li class="active">
        <a href="{{ url_for('user.view_all_posts', username=user.username) }}">
            <span class="fa fa-comment"></span> {% trans %}Posts{% endtrans %}
        </a>
    </li>
</ul>
{% endblock %}


{% block profile_content %}
<!-- middle column -->
<div class="col-md-9 col-sm-9 col-xs-12 profile-content">

    {% for post in posts.items %}
    <div class="panel page-panel">
        <div class="panel-heading page-head">
            <a href="{{ post.topic.url }}">{{ post.topic.title }}</a>
        </div>
        <div class="panel-body page-body topic-content">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="topic-created">
                    {{ post.date_created|format_date('%d %B %Y - %H:%M') }}
                </div>
                <div class="topic-content">
                    {{ post.content|markup }}
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="alert-message alert-message-info" role="alert">
                {% trans %}The user has not written any posts yet.{% endtrans %}
            </div>
        </div>
    </div>
    {% endfor %}

    {% if posts.items|length > 1 %}
    <div class="col-md-12 col-sm-12 col-xs-12 controls-col">
        <div class="pull-left">
            {{ render_pagination(posts, url_for('user.view_all_posts', username=user.username)) }}
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}

flaskbb/templates/user/all_topics.html
{% extends theme("user/profile_layout.html") %}
{% from theme('macros.html') import render_pagination, topic_pages %}

{% block breadcrumb %}
<ul class="breadcrumb flaskbb-breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
    <li class="active">{% trans %}Topics{% endtrans %}</li>
</ul>
{% endblock %}

{% block profile_navigation %}
<ul class="nav profile-sidenav" id="profile-tabs" role="tablist">
    <li>
        <a href="{{ user.url }}">
            <span class="fa fa-home"></span> {% trans %}Overview{% endtrans %}
        </a>
    </li>
    {#
    <li>
        <a href="{{ user.url }}">
            <span class="fa fa-line-chart"></span> {% trans %}Statistics{% endtrans %}
        </a>
    </li>
    #}
    <li class="active">
        <a href="{{ url_for('user.view_all_topics', username=user.username) }}">
            <span class="fa fa-comments"></span> {% trans %}Topics{% endtrans %}
        </a>
    </li>

    <li>
        <a href="{{ url_for('user.view_all_posts', username=user.username) }}">
            <span class="fa fa-comment"></span> {% trans %}Posts{% endtrans %}
        </a>
    </li>
</ul>
{% endblock %}

{% block profile_content %}
<!-- middle column -->
<div class="col-md-9 col-sm-9 col-xs-12 profile-content">

    {% for topic in topics.items %}

    <div class="panel page-panel">
        <div class="panel-heading page-head topic-head">
            <strong><a href="{{ topic.url }}">{{ topic.title }}</a></strong> in <a href="{{ topic.forum.url }}">{{ topic.forum.title }}</a>
        </div>

        <div class="panel-body page-body topic-content">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="topic-created">
                    {{ topic.date_created|format_date('%d %B %Y - %H:%M') }}
                </div>
                <div class="topic-content">
                {{ topic.first_post.content|markup }}
                </div>
            </div>
        </div>
    </div>

    {% else %}
    <div class="row">
        <div class="col-md-12 col-sm-12 co-xs-12">
            <div class="alert-message alert-message-info" role="alert">
                {% trans %}The user has not opened any topics yet.{% endtrans %}
            </div>
        </div>
    </div> <!-- end forum-row -->
    {% endfor %}

    {% if topics.items|length > 1 %}
    <div class="col-md-12 col-sm-12 col-xs-12 controls-col">
        <div class="pull-left">
            {{ render_pagination(topics, url_for('user.view_all_topics', username=user.username)) }}
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}

flaskbb/templates/user/profile.html
{% extends theme("user/profile_layout.html") %}

{% block breadcrumb %}
<ul class="breadcrumb flaskbb-breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
    <li class="active">{{ user.username }}</li>
</ul>
{% endblock %}

{% block profile_content %}
<!-- middle column -->
<div class="col-md-9 col-sm-9 col-xs-12 profile-content">


    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="overview">

            <div class="panel page-panel">
                <div class="panel-heading page-head">{% trans %}Info{% endtrans %}</div>
                <div class="panel-body page-body">
                    <div class="col-md-12 col-sm-12 col-xs-12 profile-field">
                    {% if user.notes %}
                        {{ user.notes|markup }}
                    {% else %}
                        <p>{% trans %}User has not added any notes about him.{% endtrans %}</p>
                    {% endif %}
                    </div>
                </div>
            </div> <!-- end profile widget -->


            {% if user.signature %}
            <div class="panel page-panel">
                <div class="panel-heading page-head">{% trans %}Signature{% endtrans %}</div>
                <div class="panel-body page-body">
                    <div class="col-md-12 col-sm-12 col-xs-12 profile-field">
                        {{ user.signature|markup }}
                    </div>
                </div>
            </div> <!-- end profile widget -->
            {% endif %}

        </div>
        {# Other information available for use:
         # TODO: eventually use the information (i don't how i should represent it.. any ideas?)
        <div role="tabpanel" class="tab-pane" id="info">
            <div>
                {% trans %}Group{% endtrans %}:
                {{ user.primary_group.name }}
            </div>
            <div>
                {% trans %}Joined{% endtrans %}:
                {{ user.date_joined|format_date('%b %d %Y') }}
            </div>
            <div>
                {% trans %}Posts{% endtrans %}:
                {{ user.post_count }} ({{ user.posts_per_day }} per day)
            </div>
            <div>
                {% trans %}Last seen{% endtrans %}:
                {%- if user.lastseen -%} {{ user.lastseen|time_since }} {%- else -%} {% trans %}Never seen{% endtrans %} {%- endif -%}
            </div>
            <div>
                {% trans %}Last post{% endtrans %}:
                {%- if user.last_post -%}
                    <a href="{{ user.last_post.url }}">{{ user.last_post.date_created|time_since }}</a>
                {%- else -%}
                    {% trans %}Never{% endtrans %}
                {%- endif -%}
            </div>
            <div>
                {% trans %}Location{% endtrans %}:
                {%- if user.location -%} {{ user.location }} {%- else -%} {% trans %}No Info{% endtrans %} {%- endif -%}
            </div>
            <div>
                {% trans %}Birthday{% endtrans %}:
                {% if user.birthday %}
                    {{ user.birthday|format_date('%b %d %Y') }}
                {% else %}
                    {% trans %}No Info{% endtrans %}
                {% endif %}
                {% if user.gender %}
                    ({{ user.gender }})
                {% endif %}
            </div>
        </div>
        #}
    </div>
</div> <!-- end col -->
{% endblock %}

flaskbb/templates/user/profile_layout.html
{% extends theme("layout.html") %}
{% block content %}

{% block breadcrumb %}
{% endblock %}

<div class="page-view">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="panel page-panel">
                <div class="panel-heading page-head">
                    <a href="{{ user.url }}">{{ user.username }}</a>
                </div>
                <div class="panel-body page-body profile-body">
                    {% block profile_sidebar %}
                    <div class="col-md-3 col-sm-3 col-xs-12 profile-sidebar">
                        <div class="profile-picture">
                            {% if user.avatar %}
                            <img src="{{ user.avatar }}" alt="{{ user.username }}'s Avatar">
                            {% endif %}
                        </div>

                        <div class="profile-groupname">
                            {{ user.primary_group.name }}
                        </div>

                        <div class="profile-online" data-toggle="tooltip" data-placement="top" title="{%- if user.lastseen -%} {{ user.lastseen|time_since }} {%- else -%} {% trans %}Never seen{% endtrans %} {%- endif -%}">
                            {%- if user|is_online %}
                            <span class="label label-success">online</span>
                            {%- else %}
                            <span class="label label-default">offline</span>
                            {%- endif %}
                        </div>

                        <div class="profile-sidebar-stats">
                            <div class="profile-posts">
                                {{ user.post_count }} posts
                            </div>

                            <div class="profile-date">
                                {{ user.date_joined|format_date('%b %d %Y') }}
                            </div>

                            <div class="profile-buttons">
                                {% if current_user.is_authenticated %}
                                <a class="btn btn-primary" href="{{url_for('message.new_conversation') }}?to_user={{ user.username }}">
                                    {% trans %}Message{% endtrans %}
                                </a>
                                {% endif %}
                            </div>
                        </div>

                        {% block profile_navigation %}
                        <ul class="nav profile-sidenav" id="profile-tabs" role="tablist">
                            <li class="active">
                                <a href="{{ user.url }}#overview" role="tab" data-toggle="tab">
                                    <span class="fa fa-home"></span> {% trans %}Overview{% endtrans %}
                                </a>
                            </li>
                            {#
                            <li>
                                <a href="{{ user.url }}#info" role="tab" data-toggle="tab">
                                    <span class="fa fa-line-chart"></span> {% trans %}Statistics{% endtrans %}
                                </a>
                            </li>
                            #}
                            <li>
                                <a href="{{ url_for('user.view_all_topics', username=user.username) }}">
                                    <span class="fa fa-comments"></span> {% trans %}Topics{% endtrans %}
                                </a>
                            </li>

                            <li>
                                <a href="{{ url_for('user.view_all_posts', username=user.username) }}">
                                    <span class="fa fa-comment"></span> {% trans %}Posts{% endtrans %}
                                </a>
                            </li>
                        </ul>
                        {% endblock %}
                    </div>
                    {% endblock %}

                    {% block profile_content %}
                    {% endblock %}

                </div> <!-- end profile widget -->
            </div> <!-- end page-panel -->
        </div> <!-- end col -->
    </div> <!-- end row -->
</div> <!-- end page-view -->

{% endblock %} {# content #}

{% block scripts %}
    <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

    $('#profile-tabs a[href="#overview"]').tab('show') // Select tab by name
    //$('#profile-tabs a[href="#info"]').tab('show') // Select tab by name
    </script>
{% endblock %}

flaskbb/templates/user/settings_layout.html
{% extends theme("layout.html") %}
{% block content %}
{%- from theme('macros.html') import navlink with context -%}

<ol class="breadcrumb flaskbb-breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
    <li><a href="{{ current_user.url }}">{{ current_user.username }}</a></li>
    <li class="active">{% trans %}Settings{% endtrans %}</li>
</ol>

<div class="row">
    <div class="col-sm-3">
        <div class="sidebar">
            <ul class="nav sidenav">
                <li class="sidenav-header">{% trans %}Account Settings{% endtrans %}</li>
                {{ navlink('user.settings', _('General Settings')) }}
                {{ navlink('user.change_user_details', _('Change User Details')) }}
                {{ navlink('user.change_email', _('Change E-Mail Address')) }}
                {{ navlink('user.change_password', _('Change Password')) }}
            </ul>
        </div>
    </div><!--/.col-sm-3 -->
    <div class="col-sm-9">
        {% block settings_content %}{% endblock %}
    </div><!--/.col-sm-9 -->
</div><!--/row-->

{% endblock %}